### ISSUE TITLE
Loading an HCP surface raises an Error

### ISSUE THREAD

**Issue by gagdiez** [sdeslauriers/nimesh#2]
When trying to load a surface in subject space from the HCP dataset (/home/ggallard/HCP/100307/T1w/fsaverage_LR32k/100307.L.white.32k_fs_LR.surf.gii) using nimesh.io.load, the following exception is raised:

ValueError: A transform to the current coordinate system cannot be added.

**Comment by sdeslauriers** [comment]
The exception is raised because the file contains a transform from Tailarach to Tailarach space. nimesh refuses to add a transform to the current space of the mesh. To fix, any transforms from a space to the same space will be ignored on load.

**Comment by gagdiez** [comment]
In your code, if there's no transformation then it's asumed that the surface vertices are in the Native space?
